const KAZE_PRODUCTS = [
 {id:1,name:'KAZE Street Runner',category:'Shoes',sub:'Sneakers',price:1299,old:1599,discount:'19%',tag:'NEW',meta:'Casual • Men',sizes:['6','7','8','9','10'],colors:['#111','#ddd','#1646ff'],image:'assets/shoe-black.jpg',description:'Clean everyday sneaker with a lightweight street-ready feel.'},
 {id:2,name:'KAZE Everyday Sneaker',category:'Shoes',sub:'Casual',price:1499,old:1999,discount:'25%',tag:'BEST SELLER',meta:'Sneaker • Men',sizes:['6','7','8','9','10','11'],colors:['#fff','#111','#8791a0'],image:'assets/shoe-white.jpg',description:'Minimal white sneaker designed to work with everyday fits.'},
 {id:3,name:'KAZE Classic Runner',category:'Shoes',sub:'Running',price:1199,old:1399,discount:'14%',tag:'NEW',meta:'Casual • Men',sizes:['6','7','8','9','10'],colors:['#111','#d22','#ddd'],image:'assets/shoe-runner.jpg',description:'Sporty runner-inspired style for everyday movement.'},
 {id:4,name:'KAZE Urban Trainer',category:'Shoes',sub:'Sports',price:1699,old:1999,discount:'15%',tag:'POPULAR',meta:'Sports • Men',sizes:['7','8','9','10','11'],colors:['#111','#fff'],image:'assets/shoe-black.jpg',description:'Bold trainer silhouette with a clean urban finish.'},
 {id:5,name:'KAZE Minimal Watch',category:'Watches',sub:'Minimal',price:999,old:1299,discount:'23%',tag:'TRENDING',meta:'Everyday • One Size',sizes:['One Size'],colors:['#111','#1646ff'],image:'assets/watch-blue.jpg',description:'A minimal dial made for daily wear.'},
 {id:6,name:'KAZE Classic Watch',category:'Watches',sub:'Classic',price:1299,old:1599,discount:'19%',tag:'',meta:'Classic • One Size',sizes:['One Size'],colors:['#111','#ddd'],image:'assets/watch-blue.jpg',description:'Classic metal-watch styling that pairs with almost anything.'},
 {id:7,name:'KAZE Essential Wallet',category:'Others',sub:'Wallets',price:499,old:699,discount:'29%',tag:'',meta:'Accessory • One Size',sizes:['One Size'],colors:['#111'],image:'assets/category-other.jpg',description:'A simple everyday accessory.'},
 {id:8,name:'KAZE Sunglasses',category:'Others',sub:'Sunglasses',price:699,old:899,discount:'22%',tag:'',meta:'Accessory • One Size',sizes:['One Size'],colors:['#111','#555'],image:'assets/category-other.jpg',description:'Easy-to-style sunglasses for your daily look.'}
];
