const WHATSAPP='919946375868';
const products=KAZE_PRODUCTS;
let cart=JSON.parse(localStorage.getItem('kazeCartV4')||'[]');
let wishlist=JSON.parse(localStorage.getItem('kazeWishV4')||'[]');
const money=n=>'₹'+Number(n).toLocaleString('en-IN');
const $=s=>document.querySelector(s);
const toast=m=>{const t=$('#toast');if(!t)return;t.textContent=m;t.classList.add('show');clearTimeout(window.__toast);window.__toast=setTimeout(()=>t.classList.remove('show'),1800)};
function renderProducts(){const grid=$('#productGrid');if(!grid)return;const page=grid.dataset.category||'All';const q=($('#searchInput')?.value||'').toLowerCase().trim();const list=products.filter(p=>(page==='All'||p.category===page)&&(p.name+' '+p.sub+' '+p.meta).toLowerCase().includes(q));grid.innerHTML=list.length?list.map(p=>`<article class="product reveal"><div class="product-image">${p.tag?`<span class="badge">${p.tag}</span>`:''}<button class="heart ${wishlist.includes(p.id)?'liked':''}" data-wish="${p.id}">${wishlist.includes(p.id)?'♥':'♡'}</button><img src="${p.image}" alt="${p.name}" loading="lazy"></div><div class="product-info"><h3>${p.name}</h3><div class="meta">${p.meta}</div><div class="price-row"><span class="price">${money(p.price)}</span><span class="old">${money(p.old)}</span><span class="discount">-${p.discount}</span></div><div class="size-label">SELECT SIZE</div><div class="sizes">${p.sizes.map((s,i)=>`<button class="size ${i===0?'selected':''}" data-size="${s}" data-pid="${p.id}">${s}</button>`).join('')}</div><div class="colors">${p.colors.map((c,i)=>`<button class="color ${i===0?'selected':''}" style="background:${c}" data-color="${c}" data-pid="${p.id}"></button>`).join('')}</div><button class="add ripple" data-add="${p.id}" data-size="${p.sizes[0]}" data-color="${p.colors[0]}">▢ &nbsp; ADD TO BAG</button></div></article>`).join(''):'<div class="empty" style="grid-column:1/-1;padding:50px;text-align:center">No products found.</div>';observe();}
function counts(){const n=cart.reduce((a,x)=>a+x.qty,0);document.querySelectorAll('[data-cart-count]').forEach(x=>x.textContent=n)}
function renderCart(){const box=$('#cartItems');if(!box)return;if(!cart.length)box.innerHTML='<div style="padding:50px 10px;text-align:center;color:#687080">Your bag is empty.<br>Add your favourite KAZE products.</div>';else box.innerHTML=cart.map((x,i)=>`<div class="cart-item"><div class="cart-thumb"><img src="${x.image}" alt=""></div><div><h4>${x.name}</h4><p>Size: ${x.size} • ${x.color}</p><div class="qty"><button data-minus="${i}">−</button><span>${x.qty}</span><button data-plus="${i}">+</button><button class="remove" data-remove="${i}">Remove</button></div></div><b>${money(x.price*x.qty)}</b></div>`).join('');$('#cartTotal').textContent=money(cart.reduce((a,x)=>a+x.price*x.qty,0));counts()}
function saveCart(){localStorage.setItem('kazeCartV4',JSON.stringify(cart));renderCart()}
function openCart(){if($('#cartDrawer')){$('#cartDrawer').classList.add('open');$('#cartOverlay').classList.add('open')}}
function closeCart(){if($('#cartDrawer')){$('#cartDrawer').classList.remove('open');$('#cartOverlay').classList.remove('open')}}
function add(id,size,color){const p=products.find(x=>x.id===id);if(!p)return;const same=cart.find(x=>x.id===id&&x.size===size&&x.color===color);same?same.qty++:cart.push({...p,qty:1,size,color});saveCart();toast('Added to your bag ✓');openCart()}
function checkout(){if(!cart.length){toast('Your bag is empty');return}$('#checkoutModal').classList.add('open')}
function closeCheckout(){$('#checkoutModal')?.classList.remove('open')}
function setupMenu(){const m=$('#menuBtn'),s=$('#sideMenu'),o=$('#menuOverlay');if(!m)return;m.onclick=()=>s.classList.add('open');$('#closeMenu').onclick=()=>s.classList.remove('open');o.onclick=()=>s.classList.remove('open')}
function observe(){const io=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');io.unobserve(e.target)}}),{threshold:.08});document.querySelectorAll('.reveal:not(.visible)').forEach(x=>io.observe(x))}
document.addEventListener('click',e=>{const b=e.target.closest('.ripple');if(b){const r=document.createElement('span'),rect=b.getBoundingClientRect(),d=Math.max(rect.width,rect.height);r.className='ripple-effect';r.style.width=r.style.height=d+'px';r.style.left=e.clientX-rect.left-d/2+'px';r.style.top=e.clientY-rect.top-d/2+'px';b.appendChild(r);setTimeout(()=>r.remove(),700)}const a=e.target.closest('[data-add]');if(a)add(+a.dataset.add,a.dataset.size,a.dataset.color);const s=e.target.closest('[data-size]');if(s){document.querySelectorAll(`[data-pid="${s.dataset.pid}"].size`).forEach(x=>x.classList.remove('selected'));s.classList.add('selected');document.querySelector(`[data-add="${s.dataset.pid}"]`).dataset.size=s.dataset.size}const c=e.target.closest('[data-color]');if(c){document.querySelectorAll(`[data-pid="${c.dataset.pid}"].color`).forEach(x=>x.classList.remove('selected'));c.classList.add('selected');document.querySelector(`[data-add="${c.dataset.pid}"]`).dataset.color=c.dataset.color}const w=e.target.closest('[data-wish]');if(w){const id=+w.dataset.wish;wishlist=wishlist.includes(id)?wishlist.filter(x=>x!==id):[...wishlist,id];localStorage.setItem('kazeWishV4',JSON.stringify(wishlist));renderProducts();toast(wishlist.includes(id)?'Added to wishlist':'Removed from wishlist')}const plus=e.target.closest('[data-plus]');if(plus){cart[+plus.dataset.plus].qty++;saveCart()}const minus=e.target.closest('[data-minus]');if(minus){cart[+minus.dataset.minus].qty--;if(cart[+minus.dataset.minus].qty<=0)cart.splice(+minus.dataset.minus,1);saveCart()}const rem=e.target.closest('[data-remove]');if(rem){cart.splice(+rem.dataset.remove,1);saveCart()}});
$('#cartBtn')?.addEventListener('click',openCart);$('#mobileCart')?.addEventListener('click',openCart);$('#closeCart')?.addEventListener('click',closeCart);$('#cartOverlay')?.addEventListener('click',closeCart);$('#checkoutBtn')?.addEventListener('click',checkout);$('#closeCheckout')?.addEventListener('click',closeCheckout);$('#checkoutOverlay')?.addEventListener('click',closeCheckout);$('#whatsappFloat')?.addEventListener('click',()=>window.open(`https://wa.me/${WHATSAPP}`,'_blank'));
$('#searchBtn')?.addEventListener('click',()=>{const s=$('#searchWrap');s.classList.toggle('open');$('#searchInput').focus()});$('#mobileSearch')?.addEventListener('click',()=>{const s=$('#searchWrap');s.classList.toggle('open');$('#searchInput').focus()});$('#searchInput')?.addEventListener('input',renderProducts);
$('#checkoutForm')?.addEventListener('submit',e=>{e.preventDefault();if(!cart.length)return;const f=new FormData(e.target),items=cart.map(x=>`• ${x.name} — Size ${x.size} — ${x.qty} × ${money(x.price)}`).join('\n'),total=cart.reduce((a,x)=>a+x.price*x.qty,0);const msg=`*KAZE — NEW ORDER*\n\n*Products:*\n${items}\n\n*Subtotal:* ${money(total)}\n*Customer:* ${f.get('name')}\n*Phone:* ${f.get('phone')}\n*Delivery Address:* ${f.get('address')}\n*Notes:* ${f.get('notes')||'None'}\n\n*COD:* No`;window.open(`https://wa.me/${WHATSAPP}?text=${encodeURIComponent(msg)}`,'_blank');toast('Opening WhatsApp…');cart=[];saveCart();closeCheckout()});
setupMenu();renderProducts();renderCart();observe();document.querySelector('#year')&&(document.querySelector('#year').textContent=new Date().getFullYear());
